#!/bin/bash
# Removes local build leftovers: DerivedData, packaged .dmg files, and
# stray .DS_Store files. Safe to run any time - everything here is
# regenerated by scripts/build-and-sign-dmg.sh.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$ROOT_DIR/build"

if [ -d "$BUILD_DIR" ]; then
  echo "==> Removing $BUILD_DIR"
  rm -rf "$BUILD_DIR"
fi

echo "==> Removing stray .DS_Store files"
find "$ROOT_DIR" -name ".DS_Store" -delete

echo "Done."
