---
name: Build
permissions:
  contents: read

on:
  push:
    paths-ignore:
      - "site/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "site/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ci_version: ${{ steps.set-ci-version.outputs.ci_version }}
    steps:
      - name: Set CI version
        id: set-ci-version
        shell: bash
        run: |
          CI_VERSION=`echo ${GITHUB_SHA} | cut -c1-6`
          echo "ci_version=${CI_VERSION}" >> "${GITHUB_OUTPUT}"

  build-macos:
    needs: setup
    uses: ./.github/workflows/build-macos.yml
    with:
      ci_version: ${{ needs.setup.outputs.ci_version }}
